import { ActionColumn } from './ActionColumn';

export const columnConfig = {
    customer: [
        { Header: 'Customer Id', accessor: 'customerId' },
        { Header: 'Customer Name', accessor: 'name' },
        { Header: 'Time Created', accessor: 'createdAt' },
        { Header: 'Edit', accessor: 'action', Cell: ActionColumn },
    ],
    building: [
        { Header: 'Building  Id', accessor: 'buildingId' },
        { Header: 'Building Name', accessor: 'name' },
        { Header: 'Customer Name', accessor: 'customerName' },
        { Header: 'Cost of Energy', accessor: 'costOfEnergy' },
        { Header: 'Cost Per Sq.ft', accessor: 'costPerSqFt' },
        { Header: 'Time Created', accessor: 'createdAt' },
        { Header: 'Edit', accessor: 'action', Cell: ActionColumn },
    ],
    floor: [
        { Header: 'Floor Id', accessor: 'id' },
        { Header: 'Floor Name', accessor: 'name' },
        { Header: 'Building Name', accessor: 'building' },
        { Header: 'Customer Name', accessor: 'customer' },
        { Header: 'Time Created', accessor: 'createdAt' },
        { Header: 'Edit', accessor: 'action', Cell: ActionColumn },
    ],
    zone: [
        { Header: 'Zone Id', accessor: 'id' },
        { Header: 'Zone Name', accessor: 'name' },
        { Header: 'Floor Name', accessor: 'floor' },
        { Header: 'Building Name', accessor: 'building' },
        { Header: 'Customer Name', accessor: 'customer' },
        { Header: 'Time Created', accessor: 'createdAt' },
        { Header: 'Edit', accessor: 'action', Cell: ActionColumn },
    ],
    device: [
        { Header: 'device Id', accessor: 'deviceId' },
        { Header: 'Device Name', accessor: 'name', defaultCanSort: false },
        { Header: 'Type', accessor: 'deviceType', defaultCanSort: false },
        { Header: 'Customer', accessor: 'customer', defaultCanSort: false },
        { Header: 'Location', accessor: 'location', defaultCanSort: false },
        { Header: 'Building', accessor: 'building', defaultCanSort: false },
        { Header: 'Floor', accessor: 'floor', defaultCanSort: false },
        // { Header: 'Zone', accessor: '', defaultCanSort: false },
        { Header: 'Commissioned Data', accessor: 'createdAt', defaultCanSort: false },
        { Header: 'Edit', accessor: 'action', defaultCanSort: false, Cell: ActionColumn },
    ],
    gateway: [
        { Header: ' gateway Id', accessor: 'id' },
        { Header: 'Gateway Name', accessor: 'name', defaultCanSort: false },
        { Header: 'Customer', accessor: 'customer', defaultCanSort: false },
        { Header: 'SSID', accessor: 'ssid', defaultCanSort: false },
        { Header: 'Passw.', accessor: 'password', defaultCanSort: false },
        { Header: 'Building', accessor: 'building', defaultCanSort: false },
        { Header: 'Floor', accessor: 'floor', defaultCanSort: false },
        { Header: 'Zone', accessor: 'zone', defaultCanSort: false },
        { Header: 'Edit', accessor: 'action', defaultCanSort: false, Cell: ActionColumn },
    ],
    user: [
        { Header: 'User Name', accessor: 'name', defaultCanSort: false },
        { Header: 'Type', accessor: 'type', defaultCanSort: false },
        { Header: 'Customer', accessor: 'customer', defaultCanSort: false },
        { Header: 'Building', accessor: 'building', defaultCanSort: false },
        { Header: 'Email', accessor: 'email', defaultCanSort: false },
        { Header: 'Phone Number', accessor: 'phone', defaultCanSort: false },
        { Header: 'Created On', accessor: 'createdAt', defaultCanSort: false },
        { Header: 'Edit', accessor: 'action', defaultCanSort: false, Cell: ActionColumn },
    ],
};
