// import { DeviseTables } from './types';
// const someMillisecondValue = 511111222127; // Replace with your desired millisecond value
// const date = new Date();

// const minute = date.getMinutes();
// const hour = date.getHours();
// // const day = date.getDate();
// // const month = date.getMonth();
// // const year = date.getFullYear();
// const CurrentTime = `${hour}:${minute} hr today`;
// const data: DeviseTables[] = [
//     {
//         device_id: 'CS10475',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS10738',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS10750',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS30653',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS30821',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS30879',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS30929',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS30931',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS30947',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS30963',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },

//     {
//         device_id: 'CS30966',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4061',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4062',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4063',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4064',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4065',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4066',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4067',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4068',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4069',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4070',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4071',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4072',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4073',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4074',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4075',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4073',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4074',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4076',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4077',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4078',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4079',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS4080',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
//     {
//         device_id: 'CS5336',
//         customer: 'Panasonic',
//         seat_no: 'Bangalore',
//         building: 'Brigade Signature Towers',
//         floor: '2',
//         health_status: 'ON',
//         last_refreshed_on: CurrentTime,
//         last_diagnosed_on: '09th Jul 7:30pm',
//         battery_level: '70',
//     },
// ];

export {};
